//
//  NewsDetailShowInteractor.swift
//  YandexAutoRSS
//
//  Created by msm72 on 01.11.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business Logic protocols
protocol NewsDetailShowBusinessLogic {
    func doSomething(request: NewsDetailShowModels.Something.RequestModel)
}

protocol NewsDetailShowDataStore {
    //var name: String { get set }
}

class NewsDetailShowInteractor: NewsDetailShowBusinessLogic, NewsDetailShowDataStore {
    // MARK: - Properties
    var presenter: NewsDetailShowPresentationLogic?
    var worker: NewsDetailShowWorker?
    //var name: String = ""
    
    
    // MARK: - Business logic implementation
    func doSomething(request: NewsDetailShowModels.Something.RequestModel) {
        worker = NewsDetailShowWorker()
        worker?.doSomeWork()
        
        let responseModel = NewsDetailShowModels.Something.ResponseModel()
        presenter?.presentSomething(response: responseModel)
    }
}
