//
//  NewsDetailShowPresenter.swift
//  YandexAutoRSS
//
//  Created by msm72 on 01.11.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol NewsDetailShowPresentationLogic {
    func presentFeedItem(fromResponseModel responseModel: NewsDetailShowModels.FeedItem.ResponseModel)
}

class NewsDetailShowPresenter: NewsDetailShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: NewsDetailShowDisplayLogic?
    
    
    // MARK: - Presentation Logic implementation
    func presentFeedItem(fromResponseModel responseModel: NewsDetailShowModels.FeedItem.ResponseModel) {
        let imageURL = URL.init(string: responseModel.imageURLString ?? "")
        let viewModel = NewsDetailShowModels.FeedItem.ViewModel(title: responseModel.title, description: responseModel.description, imageURL: imageURL)
        viewController?.displayFeedItem(fromViewModel: viewModel)
    }
}
