//
//  NewsDetailShowModels.swift
//  YandexAutoRSS
//
//  Created by msm72 on 01.11.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Data models
enum NewsDetailShowModels {
    // MARK: - Use cases
    enum FeedItem {
        struct RequestModel {
        }
        
        struct ResponseModel {
            let title: String
            let description: String
            let imageURLString: String?
        }
        
        struct ViewModel {
            let title: String
            let description: String
            let imageURL: URL?
        }
    }
}
