//
//  NewsDetailShowViewController.swift
//  YandexAutoRSS
//
//  Created by msm72 on 01.11.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol NewsDetailShowDisplayLogic: class {
    func displaySomething(viewModel: NewsDetailShowModels.Something.ViewModel)
}

class NewsDetailShowViewController: UIViewController {
    // MARK: - Properties
    var interactor: NewsDetailShowBusinessLogic?
    var router: (NSObjectProtocol & NewsDetailShowRoutingLogic & NewsDetailShowDataPassing)?
    
    
    // MARK: - IBOutlets
    // @IBOutlet weak var nameTextField: UITextField!
    
    
    // MARK: - Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        
        setup()
    }
    
    
    // MARK: - Setup
    private func setup() {
        let viewController  =   self
        let interactor      =   NewsDetailShowInteractor()
        let presenter       =   NewsDetailShowPresenter()
        let router          =   NewsDetailShowRouter()
        
        viewController.interactor   =   interactor
        viewController.router       =   router
        interactor.presenter        =   presenter
        presenter.viewController    =   viewController
        router.viewController       =   viewController
        router.dataStore            =   interactor
    }
    
    
    // MARK: - Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    
    // MARK: - View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
        viewSettingsDidLoad()
    }
    
    
    // MARK: - Custom Functions
    func viewSettingsDidLoad() {
        let requestModel = NewsDetailShowModels.Something.RequestModel()
        
        interactor?.doSomething(request: requestModel)
    }
}


// MARK: - NewsDetailShowDisplayLogic
extension NewsDetailShowViewController: NewsDetailShowDisplayLogic {
    func displaySomething(viewModel: NewsDetailShowModels.Something.ViewModel) {
        // NOTE: Display the result from the Presenter
        // nameTextField.text = viewModel.name
    }
}
