//
//  NewsListShowWorker.swift
//  YandexAutoRSS
//
//  Created by msm72 on 01.11.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FeedKit

class NewsListShowWorker {
    // MARK: - Business Logic
    func fetchFeed(index: Int, completionHandler: @escaping (Result?) -> Void) {
        let rss = [
                        "https://news.yandex.ru/auto.rss",
//                        "https://news.yandex.ru/music.rss",
//                        "https://news.yandex.ru/showbusiness.rss",
//                        "https://news.yandex.ru/movies.rss",
//                        "https://news.yandex.ru/gadgets.rss",
                        "https://gazeta.ua/rss"
                    ]
        
        
        let feedURL = URL(string: rss[index])!
        let parser = FeedParser(URL: feedURL)
        
//        let url = "https://gazeta.ua/rss"
//        let parser = FeedParser(URL: URL(string: url)!)

        // Parse asynchronously, not to block the UI.
        parser?.parseAsync(queue: DispatchQueue.global(qos: .userInitiated)) { (result) in
            // Do your thing, then back to the Main thread
            DispatchQueue.main.async {
                completionHandler(result)
            }
        }
    }
}
