//
//  NewsListShowRouter.swift
//  YandexAutoRSS
//
//  Created by msm72 on 01.11.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
@objc protocol NewsListShowRoutingLogic {
    func routeToNewsDetailShowScene()
}

protocol NewsListShowDataPassing {
    var dataStore: NewsListShowDataStore? { get }
}

class NewsListShowRouter: NSObject, NewsListShowRoutingLogic, NewsListShowDataPassing {
    // MARK: - Properties
    weak var viewController: NewsListShowViewController?
    var dataStore: NewsListShowDataStore?
    
    
    // MARK: - Routing
    func routeToNewsDetailShowScene() {
        let storyboard = UIStoryboard(name: "NewsDetailShow", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "NewsDetailShowVC") as! NewsDetailShowViewController
        var destinationDS = destinationVC.router!.dataStore!
        
        passDataToNewsDetailShow(source: dataStore!, destination: &destinationDS)
        navigateToNewsDetailShow(source: viewController!, destination: destinationVC)
    }
    
    
    // MARK: - Navigation
    func navigateToNewsDetailShow(source: NewsListShowViewController, destination: NewsDetailShowViewController) {
      source.show(destination, sender: nil)
    }
    
    
    // MARK: - Passing data
    func passDataToNewsDetailShow(source: NewsListShowDataStore, destination: inout NewsDetailShowDataStore) {
        let selectedRow = (viewController?.tableView.indexPathForSelectedRow?.row)!
        destination.feedItem = source.feed!.items!.sorted(by: { $0.pubDate! > $1.pubDate! })[selectedRow]
    }
}
