//
//  NewsListShowPresenter.swift
//  YandexAutoRSS
//
//  Created by msm72 on 01.11.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol NewsListShowPresentationLogic {
    func presentSomething(response: NewsListShowModels.Something.ResponseModel)
}

class NewsListShowPresenter: NewsListShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: NewsListShowDisplayLogic?
    
    
    // MARK: - Presentation Logic implementation
    func presentSomething(response: NewsListShowModels.Something.ResponseModel) {
        let viewModel = NewsListShowModels.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
