//
//  NewsListShowModels.swift
//  YandexAutoRSS
//
//  Created by msm72 on 01.11.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AlamofireRSSParser

// MARK: - Data models
enum NewsListShowModels {
    // MARK: - Use cases
    enum FetchedFeed {
        struct RequestModel {
        }
        
        struct ResponseModel {
            var feed: RSSFeed?
        }
        
        struct ViewModel {
            struct DisplayedFeedItem {
                var title: String?
//                var date: String
//                var email: String
//                var name: String
//                var total: String
                

                
            }
            
            var displayedFeedItems: [DisplayedFeedItem]
        }
    }
}

