//
//  NewsListShowInteractor.swift
//  YandexAutoRSS
//
//  Created by msm72 on 01.11.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AlamofireRSSParser

// MARK: - Business Logic protocols
protocol NewsListShowBusinessLogic {
    func fetchFeed(withRequestModel requestModel: NewsListShowModels.FetchedFeed.RequestModel)
}

protocol NewsListShowDataStore {
    var feed: RSSFeed? { get }
}

class NewsListShowInteractor: NewsListShowBusinessLogic, NewsListShowDataStore {
    // MARK: - Properties
    var presenter: NewsListShowPresentationLogic?
    var worker: NewsListShowWorker?
    
    var feed: RSSFeed?
    
    
    // MARK: - Business logic implementation
    func fetchFeed(withRequestModel requestModel: NewsListShowModels.FetchedFeed.RequestModel) {
        worker = NewsListShowWorker()
        
        worker?.fetchFeed(completionHandler: { feed in
            self.feed = feed
            let responseModel = NewsListShowModels.FetchedFeed.ResponseModel(feed: feed)
            self.presenter?.presentFetchedFeedItems(fromResponseModel: responseModel)
        })
    }
}
